chore: add kind support for 1.25
sigstore/policy-controller pull request #229
Opened 2022-09-11 18:36 UTC by hectorj2f

#### Summary

We can now test Kubernetes v1.25. This PR adds the changes to actions so it uses v1.25.

https://github.com/kubernetes-sigs/kind/releases

#### Release Note

#### Documentation

2022-09-11 18:37 UTC, hectorj2f commented
related to https://github.com/sigstore/scaffolding/pull/343

2022-09-12 05:55 UTC, hectorj2f commented
We are blocked by https://github.com/sigstore/scaffolding/pull/343, we need to use the new scaffolding version when available.

```
 ./setup-kind.sh --registry-url registry.local:5000 --cluster-suffix cluster.local --k8s-version v1.25.x --knative-version 1.6.0
RUNNING ON Linux
Unsupported version: v1.25.x
```

2022-09-14 16:06 UTC, hectorj2f commented
This PR is blocked until a new scaffolding version gets released. 

```
+ echo 'Installing kind and knative using release'
+ curl -fLo ./setup-kind.sh https://github.com/sigstore/scaffolding/releases/download/v0.4.6/setup-kind.sh
```

2022-09-26 13:55 UTC, hectorj2f commented
scaffolding 0.4.8 was released 3d ago, we could now use that version in our tests.

2022-09-26 14:30 UTC, hectorj2f commented
@vaikas  @cpanato  This is ready now! 🎉 💃🏻

2022-09-26 14:44 UTC, cpanato commented on .github/workflows/build.yaml
> +      - uses: imjasonh/setup-ko@v0.6 # v0.6
please use the git hash instead of the tag

2022-09-26 14:45 UTC, cpanato commented on .github/workflows/kind-cluster-image-policy.yaml
> +    - uses: imjasonh/setup-ko@v0.6 # v0.6
same here

2022-09-26 14:45 UTC, cpanato commented on .github/workflows/kind-e2e-cosigned.yaml
> +    - uses: imjasonh/setup-ko@v0.6 # v0.6
and here :)

2022-09-26 14:45 UTC, cpanato commented on .github/workflows/release.yaml
> +      - uses: imjasonh/setup-ko@v0.6 # v0.6
also here :)

2022-09-26 14:45 UTC, cpanato requested changes
small change request

2022-09-26 15:42 UTC, vaikas approved these changes
Thanks!

2022-09-26 15:46 UTC, cpanato approved these changes
thank you

2022-09-26 17:06 UTC, merged